services:
  - type: web
    name: my-flask-app
    env: python
    pythonVersion: 3.11  # Use a modern Python version
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
